# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rQS6pM7TY5VJsffIr_S2yWnGT6rflV6J
"""

!yolo task=detect mode=train model=yolov8m.pt data=/content/Big-foosball-detection-dataset-2/data.yaml epochs=32 imgsz=800 plots=True